sudo: required
services: 
  - docker

before_install:
  - docker build -t alexvak/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run alexvak/react-test npm run test -- --coverage

after_success:
  - docker build -t alexvak/multi-client ./client
  - docker build -t alexvak/multi-nginx ./nginx
  - docker build -t alexvak/multi-server ./server
  - docker build -t alexvak/multi-worker ./worker
  # Login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push alexvak/multi-client
  - docker push alexvak/multi-nginx
  - docker push alexvak/multi-server
  - docker push alexvak/multi-worker